spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
      show_sql: true
    show-sql: true
    open-in-view: false

  profiles:
    include:
      - prod-db
      - prod-key
    active: prod-db, prod-key